### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by zybeich** [mr-eggplant/FOA#1]
Hi, thanks for your impressive work! When I was trying to run your code, I found there are two typos in 
https://github.com/mr-eggplant/FOA/blob/1f179a90454f7373ef0189aa99d4d1f9a3e8795e/tta_library/foa_shift.py#L22 and https://github.com/mr-eggplant/FOA/blob/1f179a90454f7373ef0189aa99d4d1f9a3e8795e/tta_library/foa.py#L22: quant_libary -> quant_library

**Comment by mr-eggplant** [comment]
Hi, thanks for your interest and kind reminder! The typos have been fixed.
